version: 2.1
jobs:
    build:
        docker: 
            - image: circleci/node:12.13-browsers # the primary container, where your job's commands are run
        
        working_directory: ~/repo
        
        steps:
            - checkout # check out the code in the project directory
            - restore_cache:
                  keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-

            - run: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            - run: yarn test

            - store_test_results:
                path: /tmp/test-results