version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13-browsers

    steps:
      - checkout
      - run:
          name: test
          command: npm test
      - store_test_results: 
          path: /tmp/test-results/res.xml