version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: echo "testcafe chrome:headless tests/test.js --reporter xunit:test-results/res.xml "
      
      - store_test_results:
          path: test-results