version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13-browsers

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: start
          command: npm start
      - run:
          name: test
          command: npm test
      - store_test_results: 
          path: /tmp/test-results.xml