version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13-browsers

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
       - restore_cache:
          key: '-v1-node-cache-{{ checksum "yarn.lock" }}-{{ arch}}'
      - run:
          name: Install App
          command: yarn
      - save_cache:
          key: '-v1-node-cache-{{ checksum "yarn.lock" }}-{{ arch }}'
          paths:
            - node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: test-results.xml
          prefix: tests
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml