version: 2.1
jobs:
    build:
        docker: 
            - image: circleci/node:12.13-browsers # the primary container, where your job's commands are run
        
        steps:
            - checkout # check out the code in the project directory
            - store_test_results:
                path: /tmp/test-results